#!/usr/bin/env python3
"""Generate the framework-coverage matrix — the executive/consulting artifact
that maps every the control plane control to the recognized AI-governance frameworks
(OWASP Agentic AI threats, NIST AI RMF, EU AI Act) and surfaces the gaps.

Reads the HAND-AUTHORED source of truth `compliance/framework-map.yaml` and emits
`docs/compliance-map.md`: one matrix per framework (rows = requirements; columns =
coverage + which the control plane control(s) satisfy them + how), a coverage summary
per framework, and an explicit gap list at the bottom cross-referenced to the
roadmap.

Pure stdlib + yaml (the host has Python, not Node). Regenerate on any change to
framework-map.yaml:
    python scripts/gen_compliance_map.py
"""
import os, sys, yaml
from collections import OrderedDict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAP_PATH = os.path.join(ROOT, "compliance", "framework-map.yaml")
MD_OUT = os.path.join(ROOT, "docs", "compliance-map.md")

COVERAGE_VALUES = ("full", "partial", "none")
COVERAGE_RANK = {"full": 3, "partial": 2, "none": 1}
COVERAGE_MARK = {"full": "✅ full", "partial": "◑ partial", "none": "✗ none"}


def load_map():
    with open(MAP_PATH, encoding="utf-8") as f:
        return yaml.safe_load(f)


def md_escape(v):
    return str(v).replace("|", "\\|")


def aggregate_coverage(entries):
    """A requirement's coverage = the WEAKEST coverage among its contributing
    controls (the conservative, auditor-honest reading: a requirement is only as
    covered as its weakest necessary control). Pure gaps (control "-") contribute
    their own coverage too. Per-control nuance is preserved in the controls cell.
    This deliberately avoids overstating: e.g. a threat whose structural control
    is only `partial` (pool-mode isolation, C1) stays `partial` even if a
    supplementary control fully covers one facet."""
    return min((e["coverage"] for e in entries), key=lambda c: COVERAGE_RANK[c])


def group_by_requirement(mappings, fw_key):
    """OrderedDict: requirement -> [entries], preserving first-seen order."""
    grouped = OrderedDict()
    for m in mappings:
        if m["framework"] != fw_key:
            continue
        grouped.setdefault(m["requirement"], []).append(m)
    return grouped


def render_framework_matrix(fw_key, fw_meta, grouped):
    L = []
    short = fw_meta.get("short", fw_key)
    L.append(f"## {fw_meta['name']}")
    L.append("")
    note = " ".join(str(fw_meta.get("version_note", "")).split())
    if note:
        L.append(f"*Version / dating:* {note}")
        L.append("")
    cols = ["Requirement", "Coverage", "the control plane control(s)", "How"]
    L.append("| " + " | ".join(cols) + " |")
    L.append("|" + "|".join("---" for _ in cols) + "|")
    for req, entries in grouped.items():
        agg = aggregate_coverage(entries)
        covered = [e for e in entries if e["control"] != "-"]
        if covered:
            ctrls = "; ".join(
                f"{md_escape(e['control'])} ({e['coverage']})" for e in covered)
        else:
            ctrls = "— (none)"
        how = " ".join(md_escape(e["how"]) for e in entries)
        L.append("| " + " | ".join([
            md_escape(req), COVERAGE_MARK[agg], ctrls, how]) + " |")
    L.append("")
    # per-framework coverage summary
    total = len(grouped)
    counts = {c: 0 for c in COVERAGE_VALUES}
    for entries in grouped.values():
        counts[aggregate_coverage(entries)] += 1
    L.append(
        f"**Coverage summary — {short}:** {counts['full']}/{total} full, "
        f"{counts['partial']}/{total} partial, {counts['none']}/{total} none.")
    L.append("")
    # gaps for this framework: any requirement not fully covered
    fw_gaps = [req for req, entries in grouped.items()
               if aggregate_coverage(entries) != "full"]
    if fw_gaps:
        L.append(f"**Gaps called out ({short}):**")
        L.append("")
        for req, entries in grouped.items():
            agg = aggregate_coverage(entries)
            if agg == "full":
                continue
            L.append(f"- **{md_escape(req)}** — {agg}: "
                     + " ".join(md_escape(e["how"]) for e in entries))
        L.append("")
    return "\n".join(L)


def render(doc):
    frameworks = doc["frameworks"]
    mappings = doc["mappings"]
    L = []
    L.append("# Framework-coverage matrix")
    L.append("")
    L.append("> GENERATED by `scripts/gen_compliance_map.py` from")
    L.append("> `compliance/framework-map.yaml` (the hand-authored source of truth) —")
    L.append("> **do not edit by hand**. Regenerate: `python scripts/gen_compliance_map.py`.")
    L.append("> See [COMPLIANCE-MAP.md](security/COMPLIANCE-MAP.md).")
    L.append("")
    L.append("Maps every the control plane control (the [GOVERNANCE.md](security/GOVERNANCE.md) control catalog) to the")
    L.append("recognized AI-governance frameworks and surfaces the gaps — the")
    L.append("executive / consulting artifact auditors ask for. Framework names are cited")
    L.append("nominatively; requirement text is summarized in our own words, not reproduced.")
    L.append("Coverage is deliberately honest: `full`, `partial`, or `none`.")
    L.append("")
    # overall summary line
    L.append("## At a glance")
    L.append("")
    L.append("| Framework | Full | Partial | None | Requirements mapped |")
    L.append("|---|---|---|---|---|")
    for fw_key, fw_meta in frameworks.items():
        grouped = group_by_requirement(mappings, fw_key)
        total = len(grouped)
        counts = {c: 0 for c in COVERAGE_VALUES}
        for entries in grouped.values():
            counts[aggregate_coverage(entries)] += 1
        L.append(f"| {md_escape(fw_meta['name'])} | {counts['full']} | "
                 f"{counts['partial']} | {counts['none']} | {total} |")
    L.append("")
    for fw_key, fw_meta in frameworks.items():
        grouped = group_by_requirement(mappings, fw_key)
        L.append(render_framework_matrix(fw_key, fw_meta, grouped))
    # curated gap list
    gaps = doc.get("gaps", [])
    if gaps:
        L.append("## Honest gap list (what the control plane does NOT yet cover)")
        L.append("")
        L.append("Cross-referenced to the E2/E3 roadmap in MARKET-ANALYSIS.md and the")
        L.append("THREAT-MODEL.md findings.")
        L.append("")
        cols = ["Gap", "Frameworks touched", "Roadmap / ref", "Note"]
        L.append("| " + " | ".join(cols) + " |")
        L.append("|" + "|".join("---" for _ in cols) + "|")
        for g in gaps:
            fws = ", ".join(g.get("frameworks", []))
            L.append("| " + " | ".join(md_escape(v) for v in [
                f"{g['id']}. {g['title']}", fws, g.get("roadmap", ""),
                g.get("note", "")]) + " |")
        L.append("")
    return "\n".join(L)


def main():
    doc = load_map()
    os.makedirs(os.path.dirname(MD_OUT), exist_ok=True)
    with open(MD_OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(render(doc))

    frameworks = doc["frameworks"]
    mappings = doc["mappings"]
    print(f"Wrote {os.path.relpath(MD_OUT, ROOT)}")
    for fw_key, fw_meta in frameworks.items():
        grouped = group_by_requirement(mappings, fw_key)
        total = len(grouped)
        counts = {c: 0 for c in COVERAGE_VALUES}
        for entries in grouped.values():
            counts[aggregate_coverage(entries)] += 1
        print(f"  {fw_meta['short']:20s} {counts['full']}/{total} full  "
              f"{counts['partial']}/{total} partial  {counts['none']}/{total} none")
    print(f"  gaps: {len(doc.get('gaps', []))}")


if __name__ == "__main__":
    main()
